# -*- coding: utf-8 -*-
"""Hindi_Stopword

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LSYc_vF0j8K9CgZsqP5KPBBbrmVdukmu

# Assignment 4: Domain-Specific Stop Word List Construction  
### Hindi Stopwords using LiHiSTO

This notebook demonstrates how to construct and utilize a domain-specific stopword list
for **Hindi** using the **LiHiSTO** resource.

**LiHiSTO** is a comprehensive list of 820 Hindi stopwords, created
through a hybrid approach: translation of English stopwords into Hindi, combined with native Hindi stopwords.

## Step 1: Load the Hindi stopword list

We download the official LiHiSTO Hindi stopword list from its GitHub repository.
"""

import requests

# URL for LiHiSTO Hindi stopwords
url = "https://raw.githubusercontent.com/semicolon123/LiHiSTO/master/src/stopwords_hindi/final_hindi_stopwords.txt"

# Download the stopwords
response = requests.get(url)
stopwords = response.text.splitlines()

print("Total stopwords:", len(stopwords))
print("First 20 stopwords:")
print(stopwords[:20])

"""## Step 2: Save the stopword list locally

We save the stopword list into a `.txt` file for further use.
"""

with open("hindi_stopwords.txt", "w", encoding="utf-8") as f:
    for word in stopwords:
        f.write(word + "\n")

print("Stopword list saved as hindi_stopwords.txt")

"""**STEP 3**

Documentation:

Stopwords are very common words in a language which are usually filtered out during natural language processing (NLP) tasks because they carry less meaningful information. Examples in English are "is", "the", "and". In Hindi, examples are "और", "लेकिन", "यह".

Objective: To demonstrate the removal of Hindi stopwords from a given text using LiHiSTO (Lightweight Hindi Stopword Tool).

Steps:

Input a Hindi text string.

Tokenize the string into words.

Remove all words that are present in the stopword list.

Output the cleaned text.

Example:
Original text: "मैं और वह स्कूल जा रहे हैं लेकिन बारिश हो रही है।"
Stopwords removed: "स्कूल जा रहे बारिश हो रही"

Conclusion: Stopword removal is an important preprocessing step in NLP which helps in focusing on meaningful words. LiHiSTO provides a simple way to filter Hindi stopwords efficiently
"""