# -*- coding: utf-8 -*-
"""nltk_stemming_lemmatization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Ubxqp8NBvswKO-O_clLznyE2OAMjMZn
"""

import nltk
from nltk.stem import PorterStemmer, LancasterStemmer, SnowballStemmer
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from nltk.corpus import wordnet

nltk_packages = [
    'punkt',
    'wordnet',
    'averaged_perceptron_tagger', # Add the missing resource
    'punkt_tab',
    'averaged_perceptron_tagger_eng'
]

for package in nltk_packages:
    try:
        nltk.data.find(f'tokenizers/{package}') if package in ['punkt', 'punkt_tab'] else nltk.data.find(f'corpora/{package}')
    except LookupError:
        nltk.download(package)

# Input Text
text = "The striped bats are hanging on their feet for best viewing from the running children."
tokens = word_tokenize(text)
print(f"Original Tokens: {tokens}\n")
print("-" * 50)

porter = PorterStemmer()
porter_stemmed = [porter.stem(token) for token in tokens]
print("Porter Stemmer Output:")
print(porter_stemmed)
print("\n" + "-" * 50)

lancaster = LancasterStemmer()
lancaster_stemmed = [lancaster.stem(token) for token in tokens]
print("Lancaster Stemmer Output (more aggressive):")
print(lancaster_stemmed)
print("\n" + "-" * 50)

snowball = SnowballStemmer(language='english')
snowball_stemmed = [snowball.stem(token) for token in tokens]
print("Snowball Stemmer Output (English):")
print(snowball_stemmed)
print("\n" + "=" * 50)

lemmatizer = WordNetLemmatizer()

# Without POS tags (assumes Noun)
lemma_no_pos = [lemmatizer.lemmatize(token) for token in tokens]
print("Lemmatizer Output (without POS tags):")
print(lemma_no_pos)
print("\n" + "-" * 50)

# Helper function to convert NLTK POS tags to WordNet POS tags
def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

# With POS tags (more accurate)
pos_tags = nltk.pos_tag(tokens)
lemma_with_pos = [lemmatizer.lemmatize(token, get_wordnet_pos(pos)) for token, pos in pos_tags]
print("Lemmatizer Output (with POS tags - accurate):")
print(lemma_with_pos)
print("\n" + "=" * 50)

print("--- Side-by-Side Comparison ---")
print(f"{'Word':<15} | {'Porter':<15} | {'Lancaster':<15} | {'Lemmatizer (POS)':<15}")
print("-" * 70)

words_to_compare = ['striped', 'bats', 'hanging', 'running', 'feet']

for word in words_to_compare:
    porter_result = porter.stem(word)
    lancaster_result = lancaster.stem(word)
    tag = next((pos for token, pos in pos_tags if token == word), None)
    lemma_result = lemmatizer.lemmatize(word, get_wordnet_pos(tag)) if tag else lemmatizer.lemmatize(word)
    print(f"{word:<15} | {porter_result:<15} | {lancaster_result:<15} | {lemma_result:<15}")