# -*- coding: utf-8 -*-
"""Vector_Space & TF-IDF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VtT8MrBhxKitgSkkNPRctYIKqM_Bgj_9

# Assignment 5: Vector Space Models
## Textual Data: Vector Space Model and TF-IDF from scratch

In this notebook, we will:
1. Preprocess a tiny dataset of text documents.
2. Build a Term-Document Matrix.
3. Compute Term Frequency (TF).
4. Compute Inverse Document Frequency (IDF).
5. Calculate TF-IDF.
6. Use Cosine Similarity to measure similarity between documents.

### Step 1: Define a tiny dataset
We will work with a small collection of documents for clarity.
"""

# Tiny dataset of documents
documents = [
    "cats are cute and fluffy",
    "dogs are loyal and friendly",
    "cats and dogs can be friends",
    "fluffy animals like cats",
    "loyal dogs are great pets"
]

documents

"""### Step 2: Preprocessing
We will tokenize and lowercase the text.
"""

import re

def preprocess(text):
    text = text.lower()
    tokens = re.findall(r'\b\w+\b', text)
    return tokens

tokenized_docs = [preprocess(doc) for doc in documents]
tokenized_docs

"""### Step 3: Build Vocabulary and Term-Document Matrix"""

from collections import defaultdict
import numpy as np
import pandas as pd

# Build vocabulary
vocab = sorted(set(word for doc in tokenized_docs for word in doc))
vocab_index = {word: i for i, word in enumerate(vocab)}

# Term-document matrix
term_doc_matrix = np.zeros((len(vocab), len(documents)), dtype=int)

for j, doc in enumerate(tokenized_docs):
    for word in doc:
        term_doc_matrix[vocab_index[word], j] += 1

# Display as DataFrame
df = pd.DataFrame(term_doc_matrix, index=vocab, columns=[f'Doc {i+1}' for i in range(len(documents))])
df

"""### Step 4: Compute Term Frequency (TF)"""

tf = np.zeros(term_doc_matrix.shape)
for j in range(term_doc_matrix.shape[1]):
    col_sum = np.sum(term_doc_matrix[:, j])
    tf[:, j] = term_doc_matrix[:, j] / col_sum

tf_df = pd.DataFrame(tf, index=vocab, columns=[f'Doc {i+1}' for i in range(len(documents))])
tf_df

"""### Step 5: Compute Inverse Document Frequency (IDF)"""

N = len(documents)
df_counts = np.sum(term_doc_matrix > 0, axis=1)
idf = np.log(N / df_counts)

idf_df = pd.DataFrame(idf, index=vocab, columns=["IDF"])
idf_df

"""### Step 6: Compute TF-IDF"""

tfidf = tf * idf[:, None]
tfidf_df = pd.DataFrame(tfidf, index=vocab, columns=[f'Doc {i+1}' for i in range(len(documents))])
tfidf_df

"""### Step 7: Cosine Similarity between documents"""

from numpy.linalg import norm

def cosine_similarity(vec1, vec2):
    return np.dot(vec1, vec2) / (norm(vec1) * norm(vec2))

similarity_matrix = np.zeros((N, N))
for i in range(N):
    for j in range(N):
        similarity_matrix[i, j] = cosine_similarity(tfidf[:, i], tfidf[:, j])

sim_df = pd.DataFrame(similarity_matrix,
                      index=[f'Doc {i+1}' for i in range(N)],
                      columns=[f'Doc {i+1}' for i in range(N)])
sim_df

"""**STEP 8:**

*DOCUMENTATION:*

In this assignment, I used a small collection of 5 documents about cats and dogs. Using a tiny dataset allows us to manually track computations and verify results easily. a small set of textual documents was represented numerically using a Vector Space Model. Each document was preprocessed by lowercasing and tokenizing words. A term-document matrix was constructed to count word occurrences. Term Frequency (TF) normalized word counts within documents:

TF
(
𝑡
,
𝑑
)
=
Count of term
𝑡
 in document
𝑑
Total terms in document
𝑑
TF(t,d)=
Total terms in document d
Count of term t in document d
	​


Inverse Document Frequency (IDF) downweighted common words across all documents:

IDF
(
𝑡
)
=
log
⁡
𝑁
Number of documents containing
𝑡
IDF(t)=log
Number of documents containing t
N
	​


Multiplying TF by IDF gave TF-IDF vectors:

TF-IDF
(
𝑡
,
𝑑
)
=
TF
(
𝑡
,
𝑑
)
×
IDF
(
𝑡
)
TF-IDF(t,d)=TF(t,d)×IDF(t)

Cosine similarity between TF-IDF vectors measured document similarity:

Cosine Similarity
(
𝐴
,
𝐵
)
=
𝐴
⋅
𝐵
∥
𝐴
∥
∥
𝐵
∥
Cosine Similarity(A,B)=
∥A∥∥B∥
A⋅B
	​


This workflow converts raw text into numeric representations that capture semantic closeness between documents.
"""