# -*- coding: utf-8 -*-
"""Word2Vec2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bC5n1MJdVZezJzr7TmPy-XT6P8fIklxO

## **# CELL 1: Setup, Hyperparameters, and Utility Functions (utils.py Content)**

This cell initializes all dependencies, defines the core constants (like embedding dimension and window size), and includes the essential mathematical and data preparation helper functions (sigmoid, clip_weights, and the data generation logic).

Note: For submission purposes, this cell contains the functionality originally defined in utils.py.
"""

# Commented out IPython magic to ensure Python compatibility.
# CELL 1: Setup, Hyperparameters, and Utility Functions
# This cell initializes all dependencies, defines the core constants, and includes the essential
# mathematical and data preparation helper functions.

import os
import numpy as np
import random
import urllib.request
import gzip
import math
import matplotlib.pyplot as plt
from collections import Counter
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

# Add this magic command to ensure plots display in the notebook
# %matplotlib inline

# --- Hyperparameters ---
WINDOW_SIZE = 3
EMBEDDING_DIM = 100
# CRITICAL FIX for Stability: Lowering the learning rate
LEARNING_RATE = 0.005
NUM_EPOCHS = 2
MIN_COUNT = 50
# Using 5M tokens to accommodate a longer run time for better quality
MAX_TOKENS = 2_000_000
NEGATIVE_SAMPLES = 5
CLIP_LIMIT = 5.0

# --- NEW WIKIPEDIA DATA SOURCE (The "First Dataset") ---
# This is a common public URL for a smaller, cleaned subset of Wikipedia text.
DATA_URL = "http://mattmahoney.net/dc/enwik9.zip"
DATA_DIR = "wiki_dataset"
DATA_FILE_NAME = "enwik9"

# --- Utility Functions (formerly in utils.py) ---

def sigmoid(x):
    """Numerically stable sigmoid function."""
    return 1 / (1 + np.exp(-np.clip(x, -500, 500)))

def clip_weights(W, limit):
    """Clips the weight matrix values between -limit and +limit."""
    return np.clip(W, -limit, limit)

def generate_training_data(words, word2idx, window_size):
    """Generates (target_index, context_index) pairs using the sliding window."""
    training_data = []
    vocab_indices = [word2idx.get(w) for w in words if w in word2idx]

    for i, target_idx in enumerate(vocab_indices):
        if target_idx is None:
            continue

        start = max(0, i - window_size)
        end = min(len(vocab_indices), i + window_size + 1)

        for j in range(start, end):
            if i != j:
                context_idx = vocab_indices[j]
                if context_idx is not None:
                    training_data.append((target_idx, context_idx))

    return training_data

def get_negative_sampling_table(word_counts, vocab_size, idx2word):
    """Creates a large pre-computed table for efficient negative sampling based on frequency^0.75."""
    word_freqs = np.array([word_counts[idx2word[i]] for i in range(vocab_size)])
    P_neg = np.power(word_freqs, 0.75)
    P_neg /= np.sum(P_neg)

    NEG_SAMPLING_TABLE_SIZE = 100000
    table = np.random.choice(vocab_size, size=NEG_SAMPLING_TABLE_SIZE, p=P_neg)
    return table

"""# CELL 2: Data Loading, Vocabulary Construction, and Initialization

This block downloads the new Wikipedia text data, tokenizes it, filters the vocabulary,
and initializes the W1 and W2 matrices.
"""

# CELL 2: Data Loading, Vocabulary Construction, and Initialization

# This block downloads the new Wikipedia text data, tokenizes it, filters the vocabulary,
# and initializes the W1 and W2 matrices.

# Step 1 & 2: Download and Extract Data
os.makedirs(DATA_DIR, exist_ok=True)
zip_path = os.path.join(DATA_DIR, os.path.basename(DATA_URL))
sample_path = os.path.join(DATA_DIR, DATA_FILE_NAME)

if not os.path.exists(zip_path):
    print(f"📥 Downloading Wikipedia data ({DATA_FILE_NAME})... (Approx 350MB).")
    urllib.request.urlretrieve(DATA_URL, zip_path)
else:
    print("✅ Dataset already downloaded.")

# Extraction for zip file
try:
    if not os.path.exists(sample_path):
        import zipfile
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            print("Extracting data...")
            zip_ref.extractall(DATA_DIR)
except Exception as e:
    print(f"FATAL ERROR: Extraction of {DATA_FILE_NAME} failed. Error: {e}")


# Step 3: Stream and Preprocess (CRITICAL FIX FOR RAM)
print("Preprocessing text (streaming line-by-line)...")
words = []
token_count = 0
try:
    with open(sample_path, "r", encoding="utf-8", errors="ignore") as f:
        # Iterate line by line instead of reading the whole file at once (f.read())
        for line in f:
            if token_count >= MAX_TOKENS:
                break

            # Simple tokenization and lowercasing
            tokens = line.strip().lower().split()

            # Efficiently extend the list and track the total count
            for token in tokens:
                if token_count < MAX_TOKENS:
                    words.append(token)
                    token_count += 1
                else:
                    break

except FileNotFoundError:
    print(f"FATAL ERROR: Data file not found at {sample_path}. Check extraction steps.")
    # Exit or raise error if running as a script

print(f"Loaded {len(words)} tokens (up to {MAX_TOKENS} limit).")

# Step 4: Build Vocabulary
word_counts = Counter(words)
vocab = [w for w, c in word_counts.items() if c >= MIN_COUNT]
word2idx = {w: i for i, w in enumerate(vocab)}
idx2word = {i: w for w, i in word2idx.items()}
vocab_size = len(vocab)
print(f"Vocabulary size after filtering: {vocab_size}")

# Step 5: Generate training data and Negative Sampling Table
training_data = generate_training_data(words, word2idx, WINDOW_SIZE)
print(f"Training pairs (Target, Context): {len(training_data)}")
neg_sampling_table = get_negative_sampling_table(word_counts, vocab_size, idx2word)
TABLE_SIZE = len(neg_sampling_table)
table_idx = 0

# Step 6: Initialize weights
INIT_RANGE = 0.5
W1 = np.random.uniform(-INIT_RANGE, INIT_RANGE, (vocab_size, EMBEDDING_DIM)) / math.sqrt(EMBEDDING_DIM)
W2 = np.random.uniform(-INIT_RANGE, INIT_RANGE, (EMBEDDING_DIM, vocab_size)) / math.sqrt(EMBEDDING_DIM)

print("Weights initialized successfully.")

"""## **# CELL 3: Skip-Gram Training Loop**

This cell executes the training process using the Skip-Gram model with Negative Sampling.

Forward Pass: Calculates the score and prediction for one positive pair and K=5 negative pairs.
Backpropagation: Updates the output matrix (W
2
​
 ) first, then uses the error contribution from all samples to update the input vector (V
in
​
 ) in the matrix (W
1
​
 ).
Stability: Weights are clipped (clip_weights) after each epoch to maintain numerical stability.
"""

# CELL 3: Skip-Gram Training Loop

# This cell executes the training process using the Skip-Gram model with Negative Sampling.
# The low learning rate (0.005) ensures numerical stability.

print(f"\n🚀 Training Word2Vec model (W_SIZE={WINDOW_SIZE}, NEG_SAMPLES={NEGATIVE_SAMPLES})...")

def get_next_negative_sample(target_idx):
    """Draws a negative sample from the precomputed table, skipping the target word."""
    global table_idx
    while True:
        negative_idx = neg_sampling_table[table_idx]
        table_idx = (table_idx + 1) % TABLE_SIZE
        if negative_idx != target_idx:
            return negative_idx

for epoch in range(NUM_EPOCHS):
    total_loss = 0
    random.shuffle(training_data)

    for target_idx, context_idx in training_data:
        v_in = W1[target_idx, :] # Target vector (from W1)

        # 1. Prepare positive and negative samples
        indices_to_update = [(context_idx, 1)] # Positive sample (label 1)
        for _ in range(NEGATIVE_SAMPLES):
            neg_idx = get_next_negative_sample(target_idx)
            if neg_idx != context_idx:
                 indices_to_update.append((neg_idx, 0)) # Negative sample (label 0)

        grad_W1_sum = np.zeros(EMBEDDING_DIM) # Accumulate gradient for the input vector

        # 2. Update W2 and accumulate gradient for W1
        for out_idx, label in indices_to_update:
            v_out = W2[:, out_idx] # Output vector (from W2)
            score = np.dot(v_in, v_out)
            prediction = sigmoid(score)
            error = prediction - label

            # Loss accumulation (Binary Cross-Entropy)
            total_loss += - (label * np.log(prediction + 1e-7) + (1 - label) * np.log(1 - prediction + 1e-7))

            # Backpropagation updates
            dW2_col = error * v_in
            W2[:, out_idx] -= LEARNING_RATE * dW2_col
            grad_W1_sum += error * v_out # Accumulate for input vector update

        # 3. Update W1 (Input Vector)
        W1[target_idx, :] -= LEARNING_RATE * grad_W1_sum

    # Apply weight clipping at the end of each epoch
    W1 = clip_weights(W1, CLIP_LIMIT)
    W2 = clip_weights(W2, CLIP_LIMIT)

    avg_loss = total_loss / (len(training_data) * (1 + NEGATIVE_SAMPLES))
    print(f"Epoch {epoch+1}/{NUM_EPOCHS}, Average Loss: {avg_loss:.4f}")

# Save the final embeddings
os.makedirs("results", exist_ok=True)
np.save("results/embeddings.npy", W1)
print("\n✅ Training complete. Final embeddings saved to results/embeddings.npy")

"""# CELL 4: Semantic Similarity Test

This block evaluates the semantic quality of the trained embeddings by calculating the Cosine Similarity between word vectors.

"""

def get_embedding(word):
    """Retrieves the trained vector for a word."""
    if word in word2idx:
        return W1[word2idx[word]]
    return None

def cosine_similarity(v1, v2):
    """Calculates the cosine of the angle between two vectors."""
    # Check for NaN values and zero vectors for stability
    if np.isnan(v1).any() or np.isnan(v2).any():
        return -1.0
    norm_v1 = np.linalg.norm(v1)
    norm_v2 = np.linalg.norm(v2)
    if norm_v1 == 0 or norm_v2 == 0:
        return -1.0
    return np.dot(v1, v2) / (norm_v1 * norm_v2)

def find_most_similar(word, top_n=5):
    """Finds the top N words with the highest cosine similarity to the query word."""
    target_vec = get_embedding(word)
    if target_vec is None or np.isnan(target_vec).any():
        return f"'{word}' not found or corrupted."

    similarities = {}
    for i in range(vocab_size):
        if idx2word[i] != word:
            sim = cosine_similarity(target_vec, W1[i])
            if sim > -1.0:
                 similarities[idx2word[i]] = sim

    sorted_similarities = sorted(similarities.items(), key=lambda item: item[1], reverse=True)
    return sorted_similarities[:top_n]

print("\n--- Semantic Similarity Test ---")

# Test 1 (Political)
test_word = "president"
similar_words = find_most_similar(test_word)
print(f"Words most similar to '{test_word}':")
if isinstance(similar_words, str):
    print(similar_words)
else:
    for word, sim in similar_words:
        print(f"  {word}: {sim:.4f}")

# Test 2 (Geographical)
test_word = "london"
similar_words = find_most_similar(test_word)
print(f"\nWords most similar to '{test_word}':")
if isinstance(similar_words, str):
    print(similar_words)
else:
    for word, sim in similar_words:
        print(f"  {word}: {sim:.4f}")

"""# CELL 5: Visualization with PCA and t-SNE

We use dimensionality reduction techniques to visualize the learned 100-dimensional vectors in 2D space.
We plot the top N_PLOT most frequent words.

"""

print("\n🖼️ Generating visualizations (PCA & t-SNE)...")
N_WORDS = 300
N_PLOT = 100

# Get the vectors for the top N_WORDS
top_words = [w for w, _ in word_counts.most_common(N_WORDS) if w in word2idx]
top_indices = [word2idx[w] for w in top_words]
vectors = W1[top_indices]

# Filter out corrupted (NaN) vectors
nan_mask = np.isnan(vectors).any(axis=1)
if np.any(nan_mask):
    print(f"⚠️ Warning: Found {np.sum(nan_mask)} vectors with NaN values. Filtering them out.")
    vectors = vectors[~nan_mask]
    filtered_top_words = [top_words[i] for i, mask in enumerate(~nan_mask) if mask]
else:
    filtered_top_words = top_words

if len(vectors) < 10:
    print("FATAL ERROR: Insufficient non-NaN vectors for visualization.")
else:

    # --- 9.1 PCA Projection (Global Structure) ---
    reduced_pca = PCA(n_components=2).fit_transform(vectors)
    plt.figure(figsize=(12, 8))
    plt.style.use('ggplot')
    plt.title(f"PCA Projection of Word Embeddings (Top {N_PLOT} Words)", fontsize=16)
    for i, word in enumerate(filtered_top_words[:N_PLOT]):
        plt.scatter(reduced_pca[i, 0], reduced_pca[i, 1], s=50, alpha=0.7)
        plt.annotate(word, (reduced_pca[i, 0], reduced_pca[i, 1]), fontsize=9, alpha=0.8)
    plt.xlabel("PCA Component 1")
    plt.ylabel("PCA Component 2")
    plt.grid(True)
    plt.tight_layout()

    plt.savefig("results/pca.png")
    plt.show()
    plt.close()

    print("🎯 PCA Visualization saved in results/pca.png")


    # --- 9.2 t-SNE Projection (Local Structure) ---
    try:
        print("⏳ Running t-SNE (This may take a minute)...")

        tsne_vectors = vectors[:N_PLOT] if len(vectors) >= N_PLOT else vectors
        tsne_words = filtered_top_words[:N_PLOT] if len(vectors) >= N_PLOT else filtered_top_words

        # Perplexity must be less than the number of points
        perplexity_val = min(30, len(tsne_vectors) - 1)
        if perplexity_val < 1:
             raise ValueError("Not enough unique vectors for t-SNE perplexity setting.")

        reduced_tsne = TSNE(n_components=2, perplexity=perplexity_val, random_state=42, n_iter=300).fit_transform(tsne_vectors)

        plt.figure(figsize=(12, 8))
        plt.style.use('ggplot')
        plt.title(f"t-SNE Projection of Word Embeddings (Top {len(tsne_vectors)} Words)", fontsize=16)
        for i, word in enumerate(tsne_words):
            plt.scatter(reduced_tsne[i, 0], reduced_tsne[i, 1], s=50, alpha=0.7)
            plt.annotate(word, (reduced_tsne[i, 0], reduced_tsne[i, 1]), fontsize=9, alpha=0.8)
        plt.xlabel("t-SNE Component 1")
        plt.ylabel("t-SNE Component 2")
        plt.grid(True)
        plt.tight_layout()
        plt.savefig("results/tsne.png")

        plt.show()

        print("🎯 t-SNE Visualization saved in results/tsne.png")

    except ValueError as e:
        print(f"t-SNE error: {e}. Check if there are enough vectors (min 10) for TSNE.")